name: "analytics"
version: "1.0.0"
config-version: 2

profile: "analytics"

model-paths: [ "models" ]

models:
  analytics:
    +meta:
      owner: "analytics"
      description: "Analytics models for health data"
      release: "1.0.0"
    staging:
      +materialized: view
      +schema: staging
      +tags: [ "staging" ]
      # +grants:
      #   select: [ 'metabase', 'superset', 'wes' ]
      health:
        +tags: [ "staging", "health" ]
      weather:
        +tags: [ "staging", "weather" ]
      espn:
        +enabled: false
      mail:
        +tags: [ "staging", "mail" ]
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: [ "intermediate" ]
      weather:
        +tags: [ "intermediate", "weather" ]
    marts:
      +materialized: table
      +schema: marts
      +tags: [ "marts" ]
      # +grants:
      #   select: [ 'metabase', 'superset', 'wes' ]
      health:
        +tags: [ "marts", "health" ]
      weather:
        +tags: [ "marts", "weather" ]
      espn:
        +enabled: false
      mail:
        +tags: [ "marts", "mail" ]
      # +grants:
      #   select: [ 'metabase', 'superset', 'wes' ]
  elementary:
    +schema: elementary
