FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime

RUN pip install --no-cache-dir \
  jupyterlab mlflow qdrant-client transformers sentence-transformers \
  scikit-learn xgboost tensorflow boto3 duckdb plotly seaborn

RUN mkdir -p /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension && \
    echo '{"theme":"JupyterLab Dark"}' \
    > /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings

WORKDIR /workspace
EXPOSE 8888

CMD ["bash", "-lc", "jupyter lab --ip=0.0.0.0 --no-browser --allow-root --ServerApp.token='' --ServerApp.trust_xheaders=True"]
