models:
- name: vw_workouts
  columns:
  - name: id
    tests: [ not_null]
  - name: person
    tests: [ not_null ]
  - name: start
    tests: [ not_null ]
  - name: workout_type
    tests: [ not_null ]

- name: vw_heart_rate_data
  columns:
  - name: date
    tests: [ not_null ]
  - name: person
    tests: [ not_null ]

- name: vw_sleep_metrics
  columns:
  - name: record_date
    tests: [ not_null ]
  - name: person
    tests: [ not_null ]
  - name: total_sleep
    tests:
    - dbt_utils.accepted_range:
        min_value: 0
        max_value: 1440 # 24hrs in minutes
