analytics:
  target: prod
  outputs:
    prod:
      type: postgres
      host: postgres
      user: analytics
      password: "{{ env_var('ANALYTICS_DB_PASSWORD') }}"
      port: 5432
      dbname: analytics
      schema: analytics
      threads: 4