version: 2

models:
  - name: fct_espn_play
    columns:
      - name: play_espn_id
        tests: [not_null, unique]
      - name: event_id
        tests: [not_null]

  - name: fct_espn_play_participant_stat
    columns:
      - name: participant_stat_pk
        tests: [not_null, unique]

  - name: fct_espn_play_team_stat
    columns:
      - name: team_stat_pk
        tests: [not_null, unique]
