import os
from dotenv import load_dotenv

# Load resolved runtime envs (generated by stack.sh) then let local .env
# override the two Docker-internal hostnames with localhost values.
load_dotenv("/opt/config/runtime/.env.core")
load_dotenv("/opt/config/runtime/.env.dagster")
load_dotenv(override=True)

# .env.core stores MinIO creds under the user-scoped names; map them to the
# generic names the backend uses so we don't need to regenerate runtime files.
if "MINIO_ACCESS_KEY" not in os.environ and "MINIO_WES_USER" in os.environ:
    os.environ["MINIO_ACCESS_KEY"] = os.environ["MINIO_WES_USER"]
if "MINIO_SECRET_KEY" not in os.environ and "MINIO_WES_PASSWORD" in os.environ:
    os.environ["MINIO_SECRET_KEY"] = os.environ["MINIO_WES_PASSWORD"]

# Prevent boto3 from trying to parse ~/.aws/credentials — we supply creds explicitly.
os.environ["AWS_SHARED_CREDENTIALS_FILE"] = "/dev/null"
os.environ["AWS_CONFIG_FILE"] = "/dev/null"

from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from db import fetch_one
from db import get_connection
from pdf_proxy import get_pdf_response
from search import search as do_search
from upload import upload_scan

app = FastAPI(title="Mail Intelligence Search API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5174",
        "http://localhost:5173",
        "http://localhost:5175",
        "https://mail.peakprecisiondata.com",
    ],
    allow_methods=["GET", "POST", "PATCH"],
    allow_headers=["Content-Type"],
)


class SearchRequest(BaseModel):
    query: str


class ActionUpdateRequest(BaseModel):
    completed: bool
    notes: str = ""


@app.post("/api/search")
def search(req: SearchRequest):
    results, mode, answer = do_search(req.query)
    return {"results": results, "mode": mode, "count": len(results), "answer": answer}


@app.patch("/api/documents/{document_id}/action")
def update_action(document_id: int, req: ActionUpdateRequest):
    from fastapi import HTTPException
    row = fetch_one(
        "SELECT id FROM mail_raw.mail_enrichments WHERE document_id = %s",
        (document_id,),
    )
    if not row:
        raise HTTPException(status_code=404, detail="Document enrichment not found")
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE mail_raw.mail_enrichments
                SET action_completed    = %s,
                    action_completed_ts = CASE WHEN %s THEN NOW() ELSE NULL END,
                    action_notes        = %s
                WHERE document_id = %s
                """,
                (req.completed, req.completed, req.notes or None, document_id),
            )
        conn.commit()
    return {"ok": True, "document_id": document_id, "completed": req.completed}


@app.get("/api/documents/{document_id}/pdf")
def get_pdf(document_id: int):
    return get_pdf_response(document_id)


@app.post("/api/upload")
async def upload(file: UploadFile = File(...)):
    key = await upload_scan(file)
    return {"ok": True, "minio_key": key}


@app.get("/healthz")
def health():
    return {"status": "ok"}
